window.PROJECTS = [
  {
    id: "house-96",
    type: "construction",
    category: ["one", "compact"],
    badge: "Популярный",
    title: "Дом 96",
    location: "Проект под строительство",
    area: "96 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Терраса 14 м²",
    price: "от 6,9 млн ₽",
    description: "Компактный одноэтажный дом с кухней-гостиной, тремя спальнями и выходом на крытую террасу.",
    image: "assets/house-96.svg",
    plan: "assets/plan-96.svg"
  },
  {
    id: "house-124",
    type: "construction",
    category: ["one"],
    badge: "Семейный",
    title: "Дом 124",
    location: "Проект под строительство",
    area: "124 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Терраса 22 м²",
    price: "от 8,5 млн ₽",
    description: "Просторная кухня-гостиная, мастер-спальня и две детские. Планировка без проходных комнат.",
    image: "assets/house-124.svg",
    plan: "assets/plan-124.svg"
  },
  {
    id: "house-158",
    type: "construction",
    category: ["two"],
    badge: "Больше пространства",
    title: "Дом 158",
    location: "Проект под строительство",
    area: "158 м²",
    bedrooms: "4 спальни",
    floors: "2 этажа",
    bathrooms: "3 санузла",
    terrace: "Кабинет + терраса",
    price: "от 10,9 млн ₽",
    description: "Двухэтажный дом для большой семьи: отдельный кабинет, мастер-блок и много мест хранения.",
    image: "assets/house-158.svg",
    plan: "assets/plan-158.svg"
  },
  {
    id: "ready-112",
    type: "ready",
    category: ["one", "compact"],
    badge: "Готовый дом",
    title: "Дом в Ольгинской",
    location: "ст. Ольгинская",
    area: "112 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Участок 5 соток",
    price: "от 9,8 млн ₽",
    description: "Готовый дом с отделкой White Box. Подходит под ипотеку, документы готовы к проверке.",
    image: "assets/ready-112.svg",
    plan: "assets/plan-112.svg"
  },
  {
    id: "ready-138",
    type: "ready",
    category: ["one"],
    badge: "Готовый дом",
    title: "Дом в Щепкине",
    location: "п. Щепкин",
    area: "138 м²",
    bedrooms: "4 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Участок 6 соток",
    price: "от 11,4 млн ₽",
    description: "Семейный дом с просторной гостиной и четырьмя спальнями. Возможна ипотека.",
    image: "assets/ready-138.svg",
    plan: "assets/plan-138.svg"
  },
  {
    id: "ready-146",
    type: "ready",
    category: ["two"],
    badge: "Готовый дом",
    title: "Дом под Новочеркасском",
    location: "Ростовская область",
    area: "146 м²",
    bedrooms: "4 спальни",
    floors: "2 этажа",
    bathrooms: "2 санузла",
    terrace: "Участок 6 соток",
    price: "от 12,1 млн ₽",
    description: "Готовый двухэтажный дом для семьи. Поможем проверить объект и оформить сделку.",
    image: "assets/ready-146.svg",
    plan: "assets/plan-146.svg"
  }
];
