window.PROJECTS = [
  {
    id: "developer-84",
    type: "construction",
    category: ["one", "compact"],
    badge: "Проект от застройщика",
    title: "Проект 84",
    location: "Дом под ключ",
    area: "83,84 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Терраса по проекту",
    price: "от 4 192 000 ₽",
    downPayment: "от 842 600 ₽",
    monthlyPayment: "от 25 133 ₽/мес.",
    description: "Компактный одноэтажный дом с просторной кухней-гостиной и продуманной планировкой для семьи.",
    image: "assets/project-83-house.png",
    plan: "assets/project-83-plan.png",
    poster: "assets/project-83-poster.png"
  },
  {
    id: "developer-87",
    type: "construction",
    category: ["one", "compact"],
    badge: "Проект от застройщика",
    title: "Проект 87",
    location: "Дом под ключ",
    area: "87,13 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Терраса по проекту",
    price: "от 4 350 000 ₽",
    downPayment: "от 874 350 ₽",
    monthlyPayment: "от 20 838 ₽/мес.",
    description: "Рациональная планировка без лишних коридоров: общая зона, три спальни и выход на террасу.",
    image: "assets/project-87-house.png",
    plan: "assets/project-87-plan.png",
    poster: "assets/project-87-poster.png"
  },
  {
    id: "developer-101",
    type: "construction",
    category: ["one", "family"],
    badge: "Популярный проект",
    title: "Проект 101",
    location: "Дом под ключ",
    area: "101,5 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Крытая терраса",
    price: "от 5 075 000 ₽",
    downPayment: "от 1 020 075 ₽",
    monthlyPayment: "от 30 427 ₽/мес.",
    description: "Семейный дом с большой кухней-гостиной, тремя изолированными спальнями и удобной террасой.",
    image: "assets/project-101-house.png",
    plan: "assets/project-101-plan.png",
    poster: "assets/project-101-poster.png"
  },
  {
    id: "developer-100",
    type: "construction",
    category: ["one", "family"],
    badge: "Проект от застройщика",
    title: "Проект 100",
    location: "Дом под ключ",
    area: "100,59 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Комплектация на выбор",
    price: "от 5 030 000 ₽",
    downPayment: "от 1 011 030 ₽",
    monthlyPayment: "от 30 157 ₽/мес.",
    description: "Современный одноэтажный дом с панорамными окнами и гибкой семейной планировкой.",
    image: "assets/project-100-house.png",
    plan: "assets/project-100-plan.png",
    poster: "assets/project-100-poster.png"
  },
  {
    id: "developer-105",
    type: "construction",
    category: ["one", "family"],
    badge: "Проект от застройщика",
    title: "Проект 105",
    location: "Дом под ключ",
    area: "104,8 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Панорамное остекление",
    price: "от 5 240 000 ₽",
    downPayment: "от 1 053 240 ₽",
    monthlyPayment: "от 31 416 ₽/мес.",
    description: "Лаконичный дом с большой общей зоной, тремя спальнями и прямым выходом во двор.",
    image: "assets/project-104-house.png",
    plan: "assets/project-104-plan.png",
    poster: "assets/project-104-poster.png"
  },
  {
    id: "developer-132",
    type: "construction",
    category: ["two", "large"],
    badge: "Двухэтажный проект",
    title: "Проект 132",
    location: "Дом под ключ",
    area: "132,17 м²",
    bedrooms: "4 спальни",
    floors: "2 этажа",
    bathrooms: "2 санузла",
    terrace: "Балкон и терраса",
    price: "от 6 600 000 ₽",
    downPayment: "от 1 326 600 ₽",
    monthlyPayment: "от 39 570 ₽/мес.",
    description: "Просторный двухэтажный дом для большой семьи с выразительным фасадом и несколькими приватными зонами.",
    image: "assets/project-132-house.png",
    plan: "assets/project-132-plan.png",
    poster: "assets/project-132-poster.png"
  }
];

window.READY_HOMES = [
  {
    id: "olg-127g",
    community: "Ольгинская",
    address: "ул. Верхне-Луговая, 127Г",
    area: "103 м²",
    areaWithTerrace: "116 м² с террасой",
    lot: "6,67 сот.",
    finish: "Предчистовая",
    price: 6600000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MTzv8",
    plan: "https://clck.ru/3MTzwE"
  },
  {
    id: "olg-127v",
    community: "Ольгинская",
    address: "ул. Верхне-Луговая, 127В",
    area: "103 м²",
    areaWithTerrace: "116 м² с террасой",
    lot: "5 сот.",
    finish: "Предчистовая",
    price: 6600000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MTzv8",
    plan: "https://clck.ru/3MTzwE"
  },
  {
    id: "olg-127b",
    community: "Ольгинская",
    address: "ул. Верхне-Луговая, 127Б",
    area: "103 м²",
    areaWithTerrace: "116 м² с террасой",
    lot: "5 сот.",
    finish: "Предчистовая",
    price: 6600000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MTzv8",
    plan: "https://clck.ru/3MTzwE"
  },
  {
    id: "olg-127a",
    community: "Ольгинская",
    address: "ул. Верхне-Луговая, 127А",
    area: "103 м²",
    areaWithTerrace: "116 м² с террасой",
    lot: "5 сот.",
    finish: "Черновая",
    price: 6300000,
    stage: "Кровля",
    status: "Свободен",
    gallery: "https://clck.ru/3MTzv8",
    plan: "https://clck.ru/3MTzwE"
  },
  {
    id: "olg-127",
    community: "Ольгинская",
    address: "ул. Верхне-Луговая, 127",
    area: "110 м²",
    areaWithTerrace: "135 м² с террасой",
    lot: "5 сот.",
    finish: "Черновая",
    price: 6500000,
    stage: "Фундамент",
    status: "Свободен",
    gallery: "https://clck.ru/3MTzv8",
    plan: "https://clck.ru/3MTzwE"
  },
  {
    id: "tem-11a",
    community: "Темерницкий",
    address: "ул. Маршала Жукова, 11А",
    area: "101 м²",
    areaWithTerrace: "113 м² с террасой",
    lot: "5,53 сот.",
    finish: "Предчистовая",
    price: 6900000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MmPYE",
    plan: "https://clck.ru/3MTzwE"
  },
  {
    id: "tem-35",
    community: "Темерницкий",
    address: "ул. Маршала Жукова, 35",
    area: "101 м²",
    areaWithTerrace: "113 м² с террасой",
    lot: "5,65 сот.",
    finish: "Предчистовая",
    price: 7100000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MmPYE",
    plan: "https://clck.ru/3MTzwE"
  },
  {
    id: "tem-35a",
    community: "Темерницкий",
    address: "ул. Маршала Жукова, 35А",
    area: "110 м²",
    areaWithTerrace: "138 м² с террасой",
    lot: "5,65 сот.",
    finish: "Предчистовая",
    price: 6700000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MmSak",
    plan: "https://drive.google.com/drive/u/0/folders/1suyMK4PVGZJK9zJnHH3nHl2BSCyFr-tb"
  },
  {
    id: "tem-35b",
    community: "Темерницкий",
    address: "ул. Маршала Жукова, 35Б",
    area: "101 м²",
    areaWithTerrace: "113 м² с террасой",
    lot: "5,67 сот.",
    finish: "Предчистовая",
    price: 7200000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MmPYE",
    plan: "https://clck.ru/3MTzwE"
  },
  {
    id: "tem-35v",
    community: "Темерницкий",
    address: "ул. Маршала Жукова, 35В",
    area: "101 м²",
    areaWithTerrace: "113 м² с террасой",
    lot: "5,67 сот.",
    finish: "Черновая",
    price: 6500000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MmPYE",
    plan: "https://clck.ru/3MTzwE"
  },
  {
    id: "tem-37",
    community: "Темерницкий",
    address: "ул. Маршала Жукова, 37",
    area: "110 м²",
    areaWithTerrace: "138 м² с террасой",
    lot: "5,67 сот.",
    finish: "Черновая",
    price: 6700000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MmSak",
    plan: "https://drive.google.com/drive/u/0/folders/1suyMK4PVGZJK9zJnHH3nHl2BSCyFr-tb"
  },
  {
    id: "tem-37a",
    community: "Темерницкий",
    address: "ул. Маршала Жукова, 37А",
    area: "101 м²",
    areaWithTerrace: "113 м² с террасой",
    lot: "5,67 сот.",
    finish: "Черновая",
    price: 6500000,
    stage: "Готов полностью",
    status: "Свободен",
    gallery: "https://clck.ru/3MmPYE",
    plan: "https://clck.ru/3MTzwE"
  }
];
