window.PROJECTS = [
  {
    id: "house-80",
    type: "construction",
    category: ["one", "compact"],
    badge: "Стартовый проект",
    title: "Дом 80",
    location: "Проект под строительство",
    area: "80 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "1 санузел",
    terrace: "Кухня-гостиная",
    price: "от 4,0 млн ₽",
    description: "Компактный одноэтажный дом для семьи: три спальни, общая кухня-гостиная и рациональная планировка без лишних метров.",
    image: "assets/house-96.svg",
    plan: "assets/plan-96.svg"
  },
  {
    id: "house-90",
    type: "construction",
    category: ["one"],
    badge: "Оптимальный",
    title: "Дом 90",
    location: "Проект под строительство",
    area: "90 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Терраса по проекту",
    price: "от 4,7 млн ₽",
    description: "Удобный семейный проект с просторной кухней-гостиной, тремя спальнями и возможностью адаптации планировки.",
    image: "assets/house-124.svg",
    plan: "assets/plan-124.svg"
  },
  {
    id: "house-100",
    type: "construction",
    category: ["one"],
    badge: "Больше пространства",
    title: "Дом 100",
    location: "Проект под строительство",
    area: "100 м²",
    bedrooms: "3–4 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Комплектация на выбор",
    price: "от 5,3 млн ₽",
    description: "Просторный одноэтажный дом с гибкой планировкой: можно предусмотреть дополнительную спальню, кабинет или гардеробную.",
    image: "assets/house-158.svg",
    plan: "assets/plan-158.svg"
  },
  {
    id: "ready-112",
    type: "ready",
    category: ["one", "compact"],
    badge: "Готовый дом",
    title: "Дом в Ольгинской",
    location: "ст. Ольгинская",
    area: "112 м²",
    bedrooms: "3 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Участок 5 соток",
    price: "цена по запросу",
    description: "Пример карточки готового объекта. После подключения шахматки здесь будут актуальные фото, планировка, цена и статус.",
    image: "assets/ready-112.svg",
    plan: "assets/plan-112.svg"
  },
  {
    id: "ready-138",
    type: "ready",
    category: ["one"],
    badge: "Готовый дом",
    title: "Дом в Щепкине",
    location: "п. Щепкин",
    area: "138 м²",
    bedrooms: "4 спальни",
    floors: "1 этаж",
    bathrooms: "2 санузла",
    terrace: "Участок 6 соток",
    price: "цена по запросу",
    description: "Пример карточки готового объекта. Актуальные данные будут перенесены из шахматки застройщика.",
    image: "assets/ready-138.svg",
    plan: "assets/plan-138.svg"
  },
  {
    id: "ready-146",
    type: "ready",
    category: ["two"],
    badge: "Готовый дом",
    title: "Дом под Новочеркасском",
    location: "Ростовская область",
    area: "146 м²",
    bedrooms: "4 спальни",
    floors: "2 этажа",
    bathrooms: "2 санузла",
    terrace: "Участок 6 соток",
    price: "цена по запросу",
    description: "Пример карточки готового объекта. После импорта шахматки будут доступны точная локация, стоимость и материалы.",
    image: "assets/ready-146.svg",
    plan: "assets/plan-146.svg"
  }
];
